### ISSUE TITLE
TypeError: db.updateText is not a function

### ISSUE THREAD

**Issue by hiimjustin000** [TrueXPixels/quick.db#146]
Making a bot called VerifyBot that protects users from spam bots.

Only problem is this:

```js
C:\Users\justi\STORAGE\6th\VerifyBot\index.js:25
        db.updateText(`messageChannel_${message.guild.id}`, newChannel).then(i => {
           ^

TypeError: db.updateText is not a function
    at Client.client.on (C:\Users\justi\STORAGE\6th\VerifyBot\index.js:25:12)
    at Client.emit (events.js:198:13)
    at MessageCreateHandler.handle (C:\Users\justi\STORAGE\6th\VerifyBot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\justi\STORAGE\6th\VerifyBot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\justi\STORAGE\6th\VerifyBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\justi\STORAGE\6th\VerifyBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)
    at WebSocket.onMessage (C:\Users\justi\STORAGE\6th\VerifyBot\node_modules\ws\lib\EventTarget.js:99:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver._receiver.onmessage (C:\Users\justi\STORAGE\6th\VerifyBot\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\Users\justi\STORAGE\6th\VerifyBot\node_modules\ws\lib\Receiver.js:389:14)
```

Yeah, some help?

**Comment by TiMuRL228** [comment]
try: db.set instead of db.updateText
