### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by Aseltic** [TrueXPixels/quick.db#152]
```
> integer@2.1.0 install /home/aseltic/Documents/QuickDB Testing/node_modules/integer
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/aseltic/Documents/QuickDB Testing/node_modules/integer/build'
gyp ERR! System Linux 4.15.0-65-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aseltic/Documents/QuickDB Testing/node_modules/integer
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN discord.js@11.5.1 requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN quickdb-testing@1.0.0 No description
npm WARN quickdb-testing@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the integer@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aseltic/.npm/_logs/2019-10-11T02_03_07_904Z-debug.log
```

**Comment by Aseltic** [comment]
I ran ``sudo npm i quick.db``

**Comment by Aseltic** [comment]
Updated error after running ``npm config set unsafe-perm=true``
```

> integer@2.1.0 install /home/aseltic/Documents/QuickDB Testing/node_modules/integer
> node-gyp rebuild

make: Entering directory '/home/aseltic/Documents/QuickDB Testing/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
  SOLINK_MODULE(target) Release/obj.target/integer.node
  COPY Release/integer.node
  COPY ../build/integer.node
  TOUCH Release/obj.target/place_resulting_binary.stamp
make: Leaving directory '/home/aseltic/Documents/QuickDB Testing/node_modules/integer/build'

> better-sqlite3@5.4.3 install /home/aseltic/Documents/QuickDB Testing/node_modules/better-sqlite3
> node-gyp rebuild

make: Entering directory '/home/aseltic/Documents/QuickDB Testing/node_modules/better-sqlite3/build'
  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
/bin/sh: 1: Testing/node_modules/better-sqlite3/build/Release/lib.host:/home/aseltic/Documents/QuickDB: not found
/home/aseltic/Documents/QuickDB Testing/node_modules/better-sqlite3/deps/extract.js:8
process.on('unhandledRejection', (err) => { throw err; });
                                            ^

CwdError: ENOENT: Cannot cd into '/home/aseltic/Documents/QuickDB Testing/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3'
    at fs.stat (/home/aseltic/Documents/QuickDB Testing/node_modules/tar/lib/mkdir.js:74:14)
    at FSReqWrap.oncomplete (fs.js:153:21)
deps/locate_sqlite3.target.mk:16: recipe for target 'b857c92884e9598d609f6be182a2595df7a8e00f.intermediate' failed
make: *** [b857c92884e9598d609f6be182a2595df7a8e00f.intermediate] Error 1
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
make: Leaving directory '/home/aseltic/Documents/QuickDB Testing/node_modules/better-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-65-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aseltic/Documents/QuickDB Testing/node_modules/better-sqlite3
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN discord.js@11.5.1 requires a peer of bufferutil@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.
npm WARN quickdb-testing@1.0.0 No description
npm WARN quickdb-testing@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@5.4.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@5.4.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aseltic/.npm/_logs/2019-10-11T15_46_29_489Z-debug.log
```

**Comment by 04b1d** [comment]
looks like an error on your end.
I may not be correct

**Comment by chills-kaden** [comment]
**How to install Quick.db on Windows**

Stuff before installation:
_- You can use CMD like the Powershell to do those steps there is not a specific terminal to use

- Node-gyp needs python 2.x and Visual C++ Build Tools.

- If you are on windows vista / 7 you will need to install the .NET Framework 4.5.1 which can be downloaded here:
https://www.microsoft.com/en-us/download/details.aspx?id=40773_


1- Click on the windows-key of your keyboard to open the windows menu

2- Type cmd/powershell (It's totally your choice) and right click on the first result

3- Click "Run as Administrator"

4- When the terminal is opened type npm install --global windows-build-tools --vs2015 in it and the installation will start. (Sometimes this can take long)

5- When the installation is finished you can close the terminal.

6- Now you must go to the directory where you want to install Quick.db.

7- Hold Left-Shift and right click on a blank space of the directory.

8- Click on "Open PowerShell window here".

9- If you see a file named "package.json" in your folder skip to 11

10- Type "npm init -y" in the terminal

11- Type npm i quick.db

Credit to Zelak-Sama for this guide.

For more questions I recommend joining the discord - [https://discord.gg/plexidev](url)

**Comment by Aseltic** [comment]
@chxlls im not on windows, i was on elemntary os but now on Zorin OS (Linux) and still have the same issue

**Comment by Aseltic** [comment]
im now on windows again and it installs just fine, linux i think i needed to be in the root user

**Comment by chxlls** [comment]
Ok, well when someone that can close this, please do so.

**Comment by NotSuggar** [comment]
S

**Comment by sredit** [comment]
What i make after? open vs code?
